const c = {
    NEW_GAME:'NEW_GAME',
    MAKE_GOAL:'MAKE_GOAL',
    COMPUTER_MAKE_GOAL:'COMPUTER_MAKE_GOAL',
    DETERMINE_WINNER:'DETERMINE_WINNER',
    DETERMINE_WINNER_AFTER_COMPUTER:'DETERMINE_WINNER_AFTER_COMPUTER',
    CLEAN_STATE:'CLEAN_STATE',
    DETERMINE_TIE:'DETERMINE_TIE'
}

export default c